// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Fortune API endpoint definition",
    "title": "Fortune API",
    "version": "1.0.0"
  },
  "paths": {
    "/fortune": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Returns a random fortune",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "fortune": {
                  "description": "Fortune message.",
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Fortune API endpoint definition",
    "title": "Fortune API",
    "version": "1.0.0"
  },
  "paths": {
    "/fortune": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Returns a random fortune",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "fortune": {
                  "description": "Fortune message.",
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
}
