// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetFortuneOKCode is the HTTP code returned for type GetFortuneOK
const GetFortuneOKCode int = 200

/*GetFortuneOK OK

swagger:response getFortuneOK
*/
type GetFortuneOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetFortuneOK creates GetFortuneOK with default headers values
func NewGetFortuneOK() *GetFortuneOK {

	return &GetFortuneOK{}
}

// WithPayload adds the payload to the get fortune o k response
func (o *GetFortuneOK) WithPayload(payload string) *GetFortuneOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get fortune o k response
func (o *GetFortuneOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFortuneOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
