swagger: "2.0"
info:
  title: Fortune API
  description: Fortune API endpoint definition
  version: 1.0.0
schemes:
  - http
paths:
  /fortune:
    get:
      summary: Returns a random fortune
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              fortune:
                type: string
                description: Fortune message.
